spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    driver-class-name: org.h2.Driver
    url: "jdbc:h2:mem:sof_server;MODE=MYSQL"
    username: admin
    password:

server:
  domain: http://ec2-54-180-55-239.ap-northeast-2.compute.amazonaws.com

logging:
  level:
    root: WARN