spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    driver-class-name: org.h2.Driver
    url: "jdbc:h2:mem:sof_server;MODE=MYSQL"
    username: admin
    password:
  jpa:
    hibernate:
      ddl-auto: create
  output:
    ansi:
      enabled: always

server:
  domain: http://localhost

decorator.datasource.p6spy:
  enable-logging: true
  multiline: true

logging:
  level:
    org:
      springframework:
        orm:
          jpa: DEBUG
